### ISSUE TITLE
tuple out of range issue

### ISSUE THREAD

**Issue by emukoya** [CarlosCujcuj/Fingerprint-Segmentation#1]
IndexError                                Traceback (most recent call last)

[<ipython-input-5-9dd81a7d807c>](https://localhost:8080/#) in <module>
     53 
     54 #plot.imgview(labelview(connected_c(imagenInput)), filename=outputImg)
---> 55 result = labelview(connected_c(imagenInput))
     56 #convert to float32 so we can convert BRG colors to RGB
     57 result = result.astype(np.float32)

[<ipython-input-4-eb196743bd18>](https://localhost:8080/#) in connected_c(img)
     25     """
     26     #threshold == 127
---> 27     img = np.array([[255 if img[j,i] > 127 else 0 for i in range(img.shape[1])] for j in range((img.shape[0]))])
     28     img = imgpad(img, 1)
     29     labels = np.full((img.shape[0], img.shape[1]), 255)

IndexError: tuple index out of range

**Comment by DotBion** [comment]
Getting the same error:
python fpSegmentation.py inputImage.png outputImageName.png
[ WARN:0@0.373] global loadsave.cpp:248 cv::findDecoder imread_('inputImage.png'): can't open/read file: check file path/integrity
Traceback (most recent call last):
  File "D:\#fp-codes\fingerprint-processing\fpSegmentation.py", line 151, in <module>
    result = labelview(connected_c(imagenInput))
  File "D:\#fp-codes\fingerprint-processing\fpSegmentation.py", line 57, in connected_c
    img = np.array([[255 if img[j,i] > 127 else 0 for i in range(img.shape[1])] for j in range((img.shape[0]))])
IndexError: tuple index out of range
